### ISSUE TITLE
Can't get the module to work

### ISSUE THREAD

**Issue by theskyisthelimit** [spitzlbergerj/MMM-TeslaLogger#1] opened 2020-03-14 05:45 UTC
Good morning,

I just got my car last week and was thrilled to have the possibility to display informations on my magicmirror. Unfortunately I am not able to get this module to work. I have the application Teslamate up and running in several docker containers. I am able to connect to the MQTT broker with a tool like "MQTT Explorer" and I can see all the stats and parameters. However on the magicmirror I can only see the values as "undefined" and the status of the car is alway offline. 

Any suggestions or things I could try?

**Comment by spitzlbergerj** [comment] 2020-03-14 07:24
hi,
MMM-TeslaLogger currently only supports TeslaLogger. But I can install TeslaMate with pleasure. Could you just send me some of the MQTT telegrams. Then I will see what I can do. That shouldn't be too difficult and should be fast.

**Comment by theskyisthelimit** [comment] 2020-03-14 07:29
Thanks for the superquick reply! I'm not sure where I can get those MQTT telegrams but this doc has all the parameters -> https://teslamate.readthedocs.io/en/latest/integrations/mqtt.html
Does that help?

**Comment by spitzlbergerj** [comment] 2020-03-14 07:30
And the easiest way will be that you take this module : https://github.com/olexs/MMM-Teslamate
:-)

**Comment by theskyisthelimit** [comment] 2020-03-14 07:33
I like your module much more ;-) and I already tried that module and can't get it to work either.

**Comment by spitzlbergerj** [comment] 2020-03-14 07:40
oh thanks :-)
I'll take a look at this. i probably have a few hours this weekend. let's see
And maybe I will be home longer because of Corona :-)

**Comment by spitzlbergerj** [comment] 2020-03-14 07:43
But the problem is that I cannot test with me, I do not have a teslamate with me. You have to do the testing then.
And one more request.
Connect again with MQTT Explorer to your MQTT Server and get the telegrams with Copy&Paste. Please send these to me.

**Comment by theskyisthelimit** [comment] 2020-03-14 07:50
Much appreciated!
Do you live in europe too?

Do you need these values? [https://imgur.com/TE57fyF](url)

**Comment by spitzlbergerj** [comment] 2020-03-14 07:55
yes, I live near Munich, Bavaria.
And yes, these values help me.

**Comment by theskyisthelimit** [comment] 2020-03-14 07:55
teslamate/cars/1/charger_actual_current
teslamate/cars/1/rated_battery_range_km
teslamate/cars/1/charge_energy_added
teslamate/cars/1/charger_power
teslamate/cars/1/healthy
teslamate/cars/1/longitude
teslamate/cars/1/est_battery_range_km
teslamate/cars/1/usable_battery_level
teslamate/cars/1/charger_voltage
teslamate/cars/1/display_name
teslamate/cars/1/latitude
teslamate/cars/1/geofence
teslamate/cars/1/ideal_battery_range_km
teslamate/cars/1/battery_level
teslamate/cars/1/time_to_full_charge
teslamate/cars/1/outside_temp
teslamate/cars/1/state
teslamate/cars/1/since
teslamate/cars/1/inside_temp
teslamate/cars/1/is_climate_on
teslamate/cars/1/update_available
teslamate/cars/1/is_preconditioning
teslamate/cars/1/locked
teslamate/cars/1/is_user_present
teslamate/cars/1/windows_open
teslamate/cars/1/version
teslamate/cars/1/heading
teslamate/cars/1/charge_limit_soc
teslamate/cars/1/sentry_mode
teslamate/cars/1/plugged_in
teslamate/cars/1/odometer
teslamate/cars/1/charge_port_door_open
teslamate/cars/1/speed

**Comment by theskyisthelimit** [comment] 2020-03-14 07:59
Nice! I live in switzerland - almost right next to you guys. Is Germany also preparing for a full quarantine?

**Comment by spitzlbergerj** [comment] 2020-03-14 08:02
yes, I think so.

**Comment by spitzlbergerj** [comment] 2020-03-14 09:23
Hi,
would you like to give it a try? So make an update to the module and change the config. 
Add there:
mqttTopics: [
			"teslamate/cars/1/+"
		 ],
But it should also work without changing the config, because MMM-TeslaLogger is now listening to both
I hope it works. Like I said, I can't test it on myself.

Attention: 
teslamate does not provide some of the data that TeslaLogger provides. This concerns the trip data and the battery heating. But teslamate does provide some data that TeslaLogger does not (yet) provide like locked states

**Comment by theskyisthelimit** [comment] 2020-03-14 12:49
Amazing! Thank you so much! I didn't have to change anything. Should we try to integrate the other data?

**Comment by spitzlbergerj** [comment] 2020-03-15 09:38
hi,I'm glad when it fits. Which other data would you have liked to have displayed?

**Comment by theskyisthelimit** [comment] 2020-03-15 10:03
What do you think about the following parameters?

teslamate/cars/1/geofence                          -> String. e.g. "Home" or "Work"
teslamate/cars/1/locked                               -> true/false
teslamate/cars/1/update_available              -> true/false
teslamate/cars/1/time_to_full_charge         -> Not 100% sure yet but I think the shows the minutes left.

**Comment by spitzlbergerj** [comment] 2020-03-15 10:32
Hi,
ok, I'll take a look.
locked should be working by now.
I close this issue now and open a new one with the new requirements. Hope that's OK

**Closed by spitzlbergerj** 2020-03-15 10:32 UTC

**Comment by theskyisthelimit** [comment] 2020-03-15 10:33
Thank you so much for your help!

**Comment by spitzlbergerj** [comment] 2020-03-15 10:34
one more question:
which style do you use?

**Comment by theskyisthelimit** [comment] 2020-03-15 10:48
I use "lines". I've just discovered that the order of elements displayed is not the same as in the config file. Is this intentional?

**Comment by spitzlbergerj** [comment] 2020-03-15 11:15
The sequence of the elements is fixed in the program code. I do not (yet) have a variable sequence. Feature request ?  :-)

**Comment by theskyisthelimit** [comment] 2020-03-28 10:17
Hi Josef,
Please excuse my absence. I've been very busy due to the Corona virus. I will fill out the feature request as soon as possible. I have a few more ideas. Maybe you can have a look at it.

**Comment by spitzlbergerj** [comment] 2020-03-28 12:29
Hi,
no problem. I was very busy too. Please open a issue for more requests and ideas
